# permissions for end users to edit cascades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cascade-editor-role
rules:
- apiGroups:
  - derecho.poanpan
  resources:
  - cascades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - derecho.poanpan
  resources:
  - cascades/status
  verbs:
  - get
