# permissions for end users to view cascades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cascade-viewer-role
rules:
- apiGroups:
  - derecho.poanpan
  resources:
  - cascades
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - derecho.poanpan
  resources:
  - cascades/status
  verbs:
  - get
