// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cascade) DeepCopyInto(out *Cascade) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cascade.
func (in *Cascade) DeepCopy() *Cascade {
	if in == nil {
		return nil
	}
	out := new(Cascade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cascade) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CascadeConfigMapFinder) DeepCopyInto(out *CascadeConfigMapFinder) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CascadeConfigMapFinder.
func (in *CascadeConfigMapFinder) DeepCopy() *CascadeConfigMapFinder {
	if in == nil {
		return nil
	}
	out := new(CascadeConfigMapFinder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CascadeList) DeepCopyInto(out *CascadeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cascade, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CascadeList.
func (in *CascadeList) DeepCopy() *CascadeList {
	if in == nil {
		return nil
	}
	out := new(CascadeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CascadeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CascadeNodeManager) DeepCopyInto(out *CascadeNodeManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CascadeNodeManager.
func (in *CascadeNodeManager) DeepCopy() *CascadeNodeManager {
	if in == nil {
		return nil
	}
	out := new(CascadeNodeManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CascadeNodeManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CascadeNodeManagerList) DeepCopyInto(out *CascadeNodeManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CascadeNodeManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CascadeNodeManagerList.
func (in *CascadeNodeManagerList) DeepCopy() *CascadeNodeManagerList {
	if in == nil {
		return nil
	}
	out := new(CascadeNodeManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CascadeNodeManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CascadeNodeManagerSpec) DeepCopyInto(out *CascadeNodeManagerSpec) {
	*out = *in
	if in.TypesSpec != nil {
		in, out := &in.TypesSpec, &out.TypesSpec
		*out = make([]CascadeType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CascadeNodeManagerSpec.
func (in *CascadeNodeManagerSpec) DeepCopy() *CascadeNodeManagerSpec {
	if in == nil {
		return nil
	}
	out := new(CascadeNodeManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CascadeNodeManagerStatus) DeepCopyInto(out *CascadeNodeManagerStatus) {
	*out = *in
	if in.TypesStatus != nil {
		in, out := &in.TypesStatus, &out.TypesStatus
		*out = make([]CascadeType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CascadeNodeManagerStatus.
func (in *CascadeNodeManagerStatus) DeepCopy() *CascadeNodeManagerStatus {
	if in == nil {
		return nil
	}
	out := new(CascadeNodeManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CascadeSpec) DeepCopyInto(out *CascadeSpec) {
	*out = *in
	out.ConfigMapFinder = in.ConfigMapFinder
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CascadeSpec.
func (in *CascadeSpec) DeepCopy() *CascadeSpec {
	if in == nil {
		return nil
	}
	out := new(CascadeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CascadeStatus) DeepCopyInto(out *CascadeStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CascadeStatus.
func (in *CascadeStatus) DeepCopy() *CascadeStatus {
	if in == nil {
		return nil
	}
	out := new(CascadeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CascadeSubgroupLayout) DeepCopyInto(out *CascadeSubgroupLayout) {
	*out = *in
	if in.MinNodesByShard != nil {
		in, out := &in.MinNodesByShard, &out.MinNodesByShard
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.MaxNodesByShard != nil {
		in, out := &in.MaxNodesByShard, &out.MaxNodesByShard
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.ReservedNodeIdByShard != nil {
		in, out := &in.ReservedNodeIdByShard, &out.ReservedNodeIdByShard
		*out = make([][]int, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]int, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.DeliveryModesByShard != nil {
		in, out := &in.DeliveryModesByShard, &out.DeliveryModesByShard
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProfilesByShard != nil {
		in, out := &in.ProfilesByShard, &out.ProfilesByShard
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AssignedNodeIdByShard != nil {
		in, out := &in.AssignedNodeIdByShard, &out.AssignedNodeIdByShard
		*out = make([][]int, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]int, len(*in))
				copy(*out, *in)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CascadeSubgroupLayout.
func (in *CascadeSubgroupLayout) DeepCopy() *CascadeSubgroupLayout {
	if in == nil {
		return nil
	}
	out := new(CascadeSubgroupLayout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CascadeType) DeepCopyInto(out *CascadeType) {
	*out = *in
	if in.SubgroupLayout != nil {
		in, out := &in.SubgroupLayout, &out.SubgroupLayout
		*out = make([]CascadeSubgroupLayout, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CascadeType.
func (in *CascadeType) DeepCopy() *CascadeType {
	if in == nil {
		return nil
	}
	out := new(CascadeType)
	in.DeepCopyInto(out)
	return out
}
